# -*- coding: utf-8 -*-
"""Aula3sub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IDWVgKLzBBDDelb2pWFT0aJLaN2lgBSX
"""

# ETE PORTO DIGITAL
# DISCIPLINA: LPCI
# PROFESSOR CLOVES
# ESTUDANTE: FÁBIO

print ('Olá, ETE PORTO DIGITAL!')